export const especialidades = [
    { id: 30001, nombre: 'Alergia e Inmunología' },
    { id: 30002, nombre: 'Alergia e inmunología Pediátrica' },
    { id: 30003, nombre: 'Anatomía Patológica' },
    { id: 30004, nombre: 'Anestesiología' },
    { id: 30005, nombre: 'Angiología General y Hemodinamia' },
    { id: 30006, nombre: 'Cardiología' },
    { id: 30007, nombre: 'Cardiología Infantil' },
    { id: 30008, nombre: 'Cirugía Cardiovascular' },
    { id: 30009, nombre: 'Cirugía Cardiovascular Pediátrica' },
    { id: 30010, nombre: 'Cirugía de Cabeza y Cuello' },
    { id: 30011, nombre: 'Cirugía de Tórax (Cirugía Torácica)' },
    { id: 30012, nombre: 'Cirugía General' },
    { id: 30013, nombre: 'Cirugía infantil (Cirugía Pediátrica)' },
    { id: 30014, nombre: 'Cirugía Plástica y Reparadora' },
    { id: 30015, nombre: 'Cirugía Vascular Periférica' },
    { id: 30016, nombre: 'Clínica Médica' },
    { id: 30017, nombre: 'Coloproctología' },
    { id: 30018, nombre: 'Dermatología' },
    { id: 30019, nombre: 'Dermatología Pediátrica' },
    { id: 30020, nombre: 'Diagnóstico por Imágenes' },
    { id: 30021, nombre: 'Electrofisiología cardíaca' },
    { id: 30022, nombre: 'Emergentología' },
    { id: 30023, nombre: 'Endocrinología' },
    { id: 30024, nombre: 'Endocrinología Infantil' },
    { id: 30025, nombre: 'Farmacología Clínica' },
    { id: 30026, nombre: 'Fisiatría (Medicina Física y Rehabilitación)' },
    { id: 30027, nombre: 'Gastroenterología' },
    { id: 30028, nombre: 'Gastroenterología Infantil' },
    { id: 30029, nombre: 'Genética Médica' },
    { id: 30030, nombre: 'Geriatría' },
    { id: 30031, nombre: 'Ginecología' },
    { id: 30032, nombre: 'Hematología' },
    { id: 30033, nombre: 'Hemoterapia e Inmunohematología' },
    { id: 30034, nombre: 'Hepatología' },
    { id: 30035, nombre: 'Hepatología Pediátrica' },
    { id: 30036, nombre: 'Infectología' },
    { id: 30037, nombre: 'Infectología Infantil' },
    { id: 30038, nombre: 'Medicina del Deporte' },
    { id: 30039, nombre: 'Medicina del Trabajo' },
    { id: 30040, nombre: 'Medicina General' },
    { id: 30041, nombre: 'Medicina Legal' },
    { id: 30042, nombre: 'Medicina Nuclear' },
    { id: 30043, nombre: 'Medicina Paliativa' },
    { id: 30044, nombre: 'Nefrología' },
    { id: 30045, nombre: 'Nefrología Infantil' },
    { id: 30046, nombre: 'Neonatología' },
    { id: 30047, nombre: 'Neumonología' },
    { id: 30048, nombre: 'Neumonología Infantil' },
    { id: 30049, nombre: 'Neurocirugía' },
    { id: 30050, nombre: 'Neurología' },
    { id: 30051, nombre: 'Neurología Infantil' },
    { id: 30052, nombre: 'Nutrición' },
    { id: 30053, nombre: 'Obstetricia' },
    { id: 30054, nombre: 'Oftalmología' },
    { id: 30055, nombre: 'Oncología' },
    { id: 30056, nombre: 'Ortopedia y Traumatología' },
    { id: 30057, nombre: 'Ortopedia y Traumatología Infantil' },
    { id: 30058, nombre: 'Otorrinolaringología' },
    { id: 30059, nombre: 'Pediatría' },
    { id: 30060, nombre: 'Psiquiatría' },
    { id: 30061, nombre: 'Psiquiatría Infanto Juvenil' },
    { id: 30062, nombre: 'Radioterapia o Terapia Radiante' },
    { id: 30063, nombre: 'Reumatología' },
    { id: 30064, nombre: 'Reumatología Infantil' },
    { id: 30065, nombre: 'Terapia Intensiva' },
    { id: 30066, nombre: 'Terapia Intensiva Infantil' },
    { id: 30067, nombre: 'Tocoginecología' },
    { id: 30068, nombre: 'Toxicología' },
    { id: 30069, nombre: 'Urología' },
    { id: 30070, nombre: 'Salud Mental Comunitaria' },
    { id: 30071, nombre: 'Gestión de Servicios de Salud' },
    { id: 30072, nombre: 'Auditoría de Servicios de Salud' },
    { id: 30073, nombre: 'Epidemiología' },
    { id: 30074, nombre: 'Salud Pública' },
]
