export const municipios_arg = [
    {
        id: 6007,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Adolfo Alsina',
        cod_departamento: '007',
    },
    {
        id: 6014,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Adolfo Gonzales Chaves',
        cod_departamento: '014',
    },
    {
        id: 6021,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Alberti',
        cod_departamento: '021',
    },
    {
        id: 6028,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Almirante Brown',
        cod_departamento: '028',
    },
    {
        id: 6035,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Avellaneda',
        cod_departamento: '035',
    },
    {
        id: 6042,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Ayacucho',
        cod_departamento: '042',
    },
    {
        id: 6049,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Azul',
        cod_departamento: '049',
    },
    {
        id: 6056,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Bahía Blanca',
        cod_departamento: '056',
    },
    {
        id: 6063,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Balcarce',
        cod_departamento: '063',
    },
    {
        id: 6070,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Baradero',
        cod_departamento: '070',
    },
    {
        id: 6077,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Arrecifes',
        cod_departamento: '077',
    },
    {
        id: 6084,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Benito Juárez',
        cod_departamento: '084',
    },
    {
        id: 6091,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Berazategui',
        cod_departamento: '091',
    },
    {
        id: 6098,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Berisso',
        cod_departamento: '098',
    },
    {
        id: 6105,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Bolívar',
        cod_departamento: '105',
    },
    {
        id: 6112,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Bragado',
        cod_departamento: '112',
    },
    {
        id: 6119,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Brandsen',
        cod_departamento: '119',
    },
    {
        id: 6126,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Campana',
        cod_departamento: '126',
    },
    {
        id: 6134,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Cañuelas',
        cod_departamento: '134',
    },
    {
        id: 6140,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Capitán Sarmiento',
        cod_departamento: '140',
    },
    {
        id: 6147,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Carlos Casares',
        cod_departamento: '147',
    },
    {
        id: 6154,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Carlos Tejedor',
        cod_departamento: '154',
    },
    {
        id: 6161,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Carmen de Areco',
        cod_departamento: '161',
    },
    {
        id: 6168,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Castelli',
        cod_departamento: '168',
    },
    {
        id: 6175,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Colón',
        cod_departamento: '175',
    },
    {
        id: 6182,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Coronel de Marina Leonardo Rosales',
        cod_departamento: '182',
    },
    {
        id: 6189,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Coronel Dorrego',
        cod_departamento: '189',
    },
    {
        id: 6196,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Coronel Pringles',
        cod_departamento: '196',
    },
    {
        id: 6203,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Coronel Suárez',
        cod_departamento: '203',
    },
    {
        id: 6210,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Chacabuco',
        cod_departamento: '210',
    },
    {
        id: 6217,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Chascomús',
        cod_departamento: '217',
    },
    {
        id: 6224,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Chivilcoy',
        cod_departamento: '224',
    },
    {
        id: 6231,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Daireaux',
        cod_departamento: '231',
    },
    {
        id: 6238,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Dolores',
        cod_departamento: '238',
    },
    {
        id: 6245,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Ensenada',
        cod_departamento: '245',
    },
    {
        id: 6252,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Escobar',
        cod_departamento: '252',
    },
    {
        id: 6260,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Esteban Echeverría',
        cod_departamento: '260',
    },
    {
        id: 6266,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Exaltación de la Cruz',
        cod_departamento: '266',
    },
    {
        id: 6270,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Ezeiza',
        cod_departamento: '270',
    },
    {
        id: 6274,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Florencio Varela',
        cod_departamento: '274',
    },
    {
        id: 6277,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Florentino Ameghino',
        cod_departamento: '277',
    },
    {
        id: 6280,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Alvarado',
        cod_departamento: '280',
    },
    {
        id: 6287,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Alvear',
        cod_departamento: '287',
    },
    {
        id: 6294,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Arenales',
        cod_departamento: '294',
    },
    {
        id: 6301,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Belgrano',
        cod_departamento: '301',
    },
    {
        id: 6308,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Guido',
        cod_departamento: '308',
    },
    {
        id: 6315,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Juan Madariaga',
        cod_departamento: '315',
    },
    {
        id: 6322,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General La Madrid',
        cod_departamento: '322',
    },
    {
        id: 6329,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Las Heras',
        cod_departamento: '329',
    },
    {
        id: 6336,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Lavalle',
        cod_departamento: '336',
    },
    {
        id: 6343,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Paz',
        cod_departamento: '343',
    },
    {
        id: 6351,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Pinto',
        cod_departamento: '351',
    },
    {
        id: 6357,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Pueyrredón',
        cod_departamento: '357',
    },
    {
        id: 6364,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Rodríguez',
        cod_departamento: '364',
    },
    {
        id: 6371,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General San Martín',
        cod_departamento: '371',
    },
    {
        id: 6385,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Viamonte',
        cod_departamento: '385',
    },
    {
        id: 6392,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'General Villegas',
        cod_departamento: '392',
    },
    {
        id: 6399,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Guaminí',
        cod_departamento: '399',
    },
    {
        id: 6406,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Hipólito Yrigoyen',
        cod_departamento: '406',
    },
    {
        id: 6408,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Hurlingham',
        cod_departamento: '408',
    },
    {
        id: 6410,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Ituzaingó',
        cod_departamento: '410',
    },
    {
        id: 6412,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'José C. Paz',
        cod_departamento: '412',
    },
    {
        id: 6413,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Junín',
        cod_departamento: '413',
    },
    {
        id: 6420,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'La Costa',
        cod_departamento: '420',
    },
    {
        id: 6427,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'La Matanza',
        cod_departamento: '427',
    },
    {
        id: 6434,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Lanús',
        cod_departamento: '434',
    },
    {
        id: 6441,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'La Plata',
        cod_departamento: '441',
    },
    {
        id: 6448,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Laprida',
        cod_departamento: '448',
    },
    {
        id: 6455,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Las Flores',
        cod_departamento: '455',
    },
    {
        id: 6462,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Leandro N. Alem',
        cod_departamento: '462',
    },
    {
        id: 6469,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Lincoln',
        cod_departamento: '469',
    },
    {
        id: 6476,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Lobería',
        cod_departamento: '476',
    },
    {
        id: 6483,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Lobos',
        cod_departamento: '483',
    },
    {
        id: 6490,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Lomas de Zamora',
        cod_departamento: '490',
    },
    {
        id: 6497,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Luján',
        cod_departamento: '497',
    },
    {
        id: 6505,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Magdalena',
        cod_departamento: '505',
    },
    {
        id: 6511,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Maipú',
        cod_departamento: '511',
    },
    {
        id: 6515,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Malvinas Argentinas',
        cod_departamento: '515',
    },
    {
        id: 6518,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Mar Chiquita',
        cod_departamento: '518',
    },
    {
        id: 6525,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Marcos Paz',
        cod_departamento: '525',
    },
    {
        id: 6532,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Mercedes',
        cod_departamento: '532',
    },
    {
        id: 6539,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Merlo',
        cod_departamento: '539',
    },
    {
        id: 6547,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Monte',
        cod_departamento: '547',
    },
    {
        id: 6553,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Monte Hermoso',
        cod_departamento: '553',
    },
    {
        id: 6560,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Moreno',
        cod_departamento: '560',
    },
    {
        id: 6568,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Morón',
        cod_departamento: '568',
    },
    {
        id: 6574,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Navarro',
        cod_departamento: '574',
    },
    {
        id: 6581,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Necochea',
        cod_departamento: '581',
    },
    {
        id: 6588,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: '9 de Julio',
        cod_departamento: '588',
    },
    {
        id: 6595,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Olavarría',
        cod_departamento: '595',
    },
    {
        id: 6602,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Patagones',
        cod_departamento: '602',
    },
    {
        id: 6609,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Pehuajó',
        cod_departamento: '609',
    },
    {
        id: 6616,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Pellegrini',
        cod_departamento: '616',
    },
    {
        id: 6623,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Pergamino',
        cod_departamento: '623',
    },
    {
        id: 6630,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Pila',
        cod_departamento: '630',
    },
    {
        id: 6638,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Pilar',
        cod_departamento: '638',
    },
    {
        id: 6644,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Pinamar',
        cod_departamento: '644',
    },
    {
        id: 6648,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Presidente Perón',
        cod_departamento: '648',
    },
    {
        id: 6651,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Puán',
        cod_departamento: '651',
    },
    {
        id: 6655,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Punta Indio',
        cod_departamento: '655',
    },
    {
        id: 6658,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Quilmes',
        cod_departamento: '658',
    },
    {
        id: 6665,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Ramallo',
        cod_departamento: '665',
    },
    {
        id: 6672,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Rauch',
        cod_departamento: '672',
    },
    {
        id: 6679,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Rivadavia',
        cod_departamento: '679',
    },
    {
        id: 6686,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Rojas',
        cod_departamento: '686',
    },
    {
        id: 6693,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Roque Pérez',
        cod_departamento: '693',
    },
    {
        id: 6700,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Saavedra',
        cod_departamento: '700',
    },
    {
        id: 6707,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Saladillo',
        cod_departamento: '707',
    },
    {
        id: 6714,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Salto',
        cod_departamento: '714',
    },
    {
        id: 6721,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Salliqueló',
        cod_departamento: '721',
    },
    {
        id: 6728,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Andrés de Giles',
        cod_departamento: '728',
    },
    {
        id: 6735,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Antonio de Areco',
        cod_departamento: '735',
    },
    {
        id: 6742,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Cayetano',
        cod_departamento: '742',
    },
    {
        id: 6749,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Fernando',
        cod_departamento: '749',
    },
    {
        id: 6756,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Isidro',
        cod_departamento: '756',
    },
    {
        id: 6760,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Miguel',
        cod_departamento: '760',
    },
    {
        id: 6763,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Nicolás',
        cod_departamento: '763',
    },
    {
        id: 6770,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Pedro',
        cod_departamento: '770',
    },
    {
        id: 6778,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'San Vicente',
        cod_departamento: '778',
    },
    {
        id: 6784,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Suipacha',
        cod_departamento: '784',
    },
    {
        id: 6791,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tandil',
        cod_departamento: '791',
    },
    {
        id: 6798,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tapalqué',
        cod_departamento: '798',
    },
    {
        id: 6805,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tigre',
        cod_departamento: '805',
    },
    {
        id: 6812,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tordillo',
        cod_departamento: '812',
    },
    {
        id: 6819,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tornquist',
        cod_departamento: '819',
    },
    {
        id: 6826,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Trenque Lauquen',
        cod_departamento: '826',
    },
    {
        id: 6833,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tres Arroyos',
        cod_departamento: '833',
    },
    {
        id: 6840,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tres de Febrero',
        cod_departamento: '840',
    },
    {
        id: 6847,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Tres Lomas',
        cod_departamento: '847',
    },
    {
        id: 6854,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: '25 de Mayo',
        cod_departamento: '854',
    },
    {
        id: 6861,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Vicente López',
        cod_departamento: '861',
    },
    {
        id: 6868,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Villa Gesell',
        cod_departamento: '868',
    },
    {
        id: 6875,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Villarino',
        cod_departamento: '875',
    },
    {
        id: 6882,
        provincia: 'Buenos Aires',
        cod_provincia: '06',
        comuna: 'Zárate',
        cod_departamento: '882',
    },
    {
        id: 10007,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Ambato',
        cod_departamento: '007',
    },
    {
        id: 10014,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Ancasti',
        cod_departamento: '014',
    },
    {
        id: 10021,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Andalgalá',
        cod_departamento: '021',
    },
    {
        id: 10028,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Antofagasta de la Sierra',
        cod_departamento: '028',
    },
    {
        id: 10035,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Belén',
        cod_departamento: '035',
    },
    {
        id: 10042,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Capayán',
        cod_departamento: '042',
    },
    {
        id: 10049,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Capital',
        cod_departamento: '049',
    },
    {
        id: 10056,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'El Alto',
        cod_departamento: '056',
    },
    {
        id: 10063,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Fray Mamerto Esquiú',
        cod_departamento: '063',
    },
    {
        id: 10070,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'La Paz',
        cod_departamento: '070',
    },
    {
        id: 10077,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Paclín',
        cod_departamento: '077',
    },
    {
        id: 10084,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Pomán',
        cod_departamento: '084',
    },
    {
        id: 10091,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Santa María',
        cod_departamento: '091',
    },
    {
        id: 10098,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Santa Rosa',
        cod_departamento: '098',
    },
    {
        id: 10105,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Tinogasta',
        cod_departamento: '105',
    },
    {
        id: 10112,
        provincia: 'Catamarca',
        cod_provincia: '10',
        comuna: 'Valle Viejo',
        cod_departamento: '112',
    },
    {
        id: 14007,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Calamuchita',
        cod_departamento: '007',
    },
    {
        id: 14014,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Capital',
        cod_departamento: '014',
    },
    {
        id: 14021,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Colón',
        cod_departamento: '021',
    },
    {
        id: 14028,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Cruz del Eje',
        cod_departamento: '028',
    },
    {
        id: 14035,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'General Roca',
        cod_departamento: '035',
    },
    {
        id: 14042,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'General San Martín',
        cod_departamento: '042',
    },
    {
        id: 14049,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Ischilín',
        cod_departamento: '049',
    },
    {
        id: 14056,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Juárez Celman',
        cod_departamento: '056',
    },
    {
        id: 14063,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Marcos Juárez',
        cod_departamento: '063',
    },
    {
        id: 14070,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Minas',
        cod_departamento: '070',
    },
    {
        id: 14077,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Pocho',
        cod_departamento: '077',
    },
    {
        id: 14084,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Presidente Roque Sáenz Peña',
        cod_departamento: '084',
    },
    {
        id: 14091,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Punilla',
        cod_departamento: '091',
    },
    {
        id: 14098,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Río Cuarto',
        cod_departamento: '098',
    },
    {
        id: 14105,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Río Primero',
        cod_departamento: '105',
    },
    {
        id: 14112,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Río Seco',
        cod_departamento: '112',
    },
    {
        id: 14119,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Río Segundo',
        cod_departamento: '119',
    },
    {
        id: 14126,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'San Alberto',
        cod_departamento: '126',
    },
    {
        id: 14133,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'San Javier',
        cod_departamento: '133',
    },
    {
        id: 14140,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'San Justo',
        cod_departamento: '140',
    },
    {
        id: 14147,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Santa María',
        cod_departamento: '147',
    },
    {
        id: 14154,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Sobremonte',
        cod_departamento: '154',
    },
    {
        id: 14161,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Tercero Arriba',
        cod_departamento: '161',
    },
    {
        id: 14168,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Totoral',
        cod_departamento: '168',
    },
    {
        id: 14175,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Tulumba',
        cod_departamento: '175',
    },
    {
        id: 14182,
        provincia: 'Córdoba',
        cod_provincia: '14',
        comuna: 'Unión',
        cod_departamento: '182',
    },
    {
        id: 18007,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Bella Vista',
        cod_departamento: '007',
    },
    {
        id: 18014,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Berón de Astrada',
        cod_departamento: '014',
    },
    {
        id: 18021,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Capital',
        cod_departamento: '021',
    },
    {
        id: 18028,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Concepción',
        cod_departamento: '028',
    },
    {
        id: 18035,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Curuzú Cuatiá',
        cod_departamento: '035',
    },
    {
        id: 18042,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Empedrado',
        cod_departamento: '042',
    },
    {
        id: 18049,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Esquina',
        cod_departamento: '049',
    },
    {
        id: 18056,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'General Alvear',
        cod_departamento: '056',
    },
    {
        id: 18063,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'General Paz',
        cod_departamento: '063',
    },
    {
        id: 18070,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Goya',
        cod_departamento: '070',
    },
    {
        id: 18077,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Itatí',
        cod_departamento: '077',
    },
    {
        id: 18084,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Ituzaingó',
        cod_departamento: '084',
    },
    {
        id: 18091,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Lavalle',
        cod_departamento: '091',
    },
    {
        id: 18098,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Mburucuyá',
        cod_departamento: '098',
    },
    {
        id: 18105,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Mercedes',
        cod_departamento: '105',
    },
    {
        id: 18112,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Monte Caseros',
        cod_departamento: '112',
    },
    {
        id: 18119,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Paso de los Libres',
        cod_departamento: '119',
    },
    {
        id: 18126,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Saladas',
        cod_departamento: '126',
    },
    {
        id: 18133,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'San Cosme',
        cod_departamento: '133',
    },
    {
        id: 18140,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'San Luis del Palmar',
        cod_departamento: '140',
    },
    {
        id: 18147,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'San Martín',
        cod_departamento: '147',
    },
    {
        id: 18154,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'San Miguel',
        cod_departamento: '154',
    },
    {
        id: 18161,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'San Roque',
        cod_departamento: '161',
    },
    {
        id: 18168,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Santo Tomé',
        cod_departamento: '168',
    },
    {
        id: 18175,
        provincia: 'Corrientes',
        cod_provincia: '18',
        comuna: 'Sauce',
        cod_departamento: '175',
    },
    {
        id: 22007,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Almirante Brown',
        cod_departamento: '007',
    },
    {
        id: 22014,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Bermejo',
        cod_departamento: '014',
    },
    {
        id: 22021,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Comandante Fernández',
        cod_departamento: '021',
    },
    {
        id: 22028,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Chacabuco',
        cod_departamento: '028',
    },
    {
        id: 22036,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: '12 de Octubre',
        cod_departamento: '036',
    },
    {
        id: 22039,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: '2 de Abril',
        cod_departamento: '039',
    },
    {
        id: 22043,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Fray Justo Santa María de Oro',
        cod_departamento: '043',
    },
    {
        id: 22049,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'General Belgrano',
        cod_departamento: '049',
    },
    {
        id: 22056,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'General Donovan',
        cod_departamento: '056',
    },
    {
        id: 22063,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'General Güemes',
        cod_departamento: '063',
    },
    {
        id: 22070,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Independencia',
        cod_departamento: '070',
    },
    {
        id: 22077,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Libertad',
        cod_departamento: '077',
    },
    {
        id: 22084,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Libertador General San Martín',
        cod_departamento: '084',
    },
    {
        id: 22091,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Maipú',
        cod_departamento: '091',
    },
    {
        id: 22098,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Mayor Luis J. Fontana',
        cod_departamento: '098',
    },
    {
        id: 22105,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: '9 de Julio',
        cod_departamento: '105',
    },
    {
        id: 22112,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: "O'Higgins",
        cod_departamento: '112',
    },
    {
        id: 22119,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Presidencia de la Plaza',
        cod_departamento: '119',
    },
    {
        id: 22126,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: '1º de Mayo',
        cod_departamento: '126',
    },
    {
        id: 22133,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Quitilipi',
        cod_departamento: '133',
    },
    {
        id: 22140,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'San Fernando',
        cod_departamento: '140',
    },
    {
        id: 22147,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'San Lorenzo',
        cod_departamento: '147',
    },
    {
        id: 22154,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Sargento Cabral',
        cod_departamento: '154',
    },
    {
        id: 22161,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: 'Tapenagá',
        cod_departamento: '161',
    },
    {
        id: 22168,
        provincia: 'Chaco',
        cod_provincia: '22',
        comuna: '25 de Mayo',
        cod_departamento: '168',
    },
    {
        id: 26007,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Biedma',
        cod_departamento: '007',
    },
    {
        id: 26014,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Cushamen',
        cod_departamento: '014',
    },
    {
        id: 26021,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Escalante',
        cod_departamento: '021',
    },
    {
        id: 26028,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Florentino Ameghino',
        cod_departamento: '028',
    },
    {
        id: 26035,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Futaleufú',
        cod_departamento: '035',
    },
    {
        id: 26042,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Gaiman',
        cod_departamento: '042',
    },
    {
        id: 26049,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Gastre',
        cod_departamento: '049',
    },
    {
        id: 26056,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Languiñeo',
        cod_departamento: '056',
    },
    {
        id: 26063,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Mártires',
        cod_departamento: '063',
    },
    {
        id: 26070,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Paso de Indios',
        cod_departamento: '070',
    },
    {
        id: 26077,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Rawson',
        cod_departamento: '077',
    },
    {
        id: 26084,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Río Senguer',
        cod_departamento: '084',
    },
    {
        id: 26091,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Sarmiento',
        cod_departamento: '091',
    },
    {
        id: 26098,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Tehuelches',
        cod_departamento: '098',
    },
    {
        id: 26105,
        provincia: 'Chubut',
        cod_provincia: '26',
        comuna: 'Telsen',
        cod_departamento: '105',
    },
    {
        id: 30008,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Colón',
        cod_departamento: '008',
    },
    {
        id: 30015,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Concordia',
        cod_departamento: '015',
    },
    {
        id: 30021,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Diamante',
        cod_departamento: '021',
    },
    {
        id: 30028,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Federación',
        cod_departamento: '028',
    },
    {
        id: 30035,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Federal',
        cod_departamento: '035',
    },
    {
        id: 30042,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Feliciano',
        cod_departamento: '042',
    },
    {
        id: 30049,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Gualeguay',
        cod_departamento: '049',
    },
    {
        id: 30056,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Gualeguaychú',
        cod_departamento: '056',
    },
    {
        id: 30063,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Islas del Ibicuy',
        cod_departamento: '063',
    },
    {
        id: 30070,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'La Paz',
        cod_departamento: '070',
    },
    {
        id: 30077,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Nogoyá',
        cod_departamento: '077',
    },
    {
        id: 30084,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Paraná',
        cod_departamento: '084',
    },
    {
        id: 30088,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'San Salvador',
        cod_departamento: '088',
    },
    {
        id: 30091,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Tala',
        cod_departamento: '091',
    },
    {
        id: 30098,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Uruguay',
        cod_departamento: '098',
    },
    {
        id: 30105,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Victoria',
        cod_departamento: '105',
    },
    {
        id: 30113,
        provincia: 'Entre Ríos',
        cod_provincia: '30',
        comuna: 'Villaguay',
        cod_departamento: '113',
    },
    {
        id: 34007,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Bermejo',
        cod_departamento: '007',
    },
    {
        id: 34014,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Formosa',
        cod_departamento: '014',
    },
    {
        id: 34021,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Laishi',
        cod_departamento: '021',
    },
    {
        id: 34028,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Matacos',
        cod_departamento: '028',
    },
    {
        id: 34035,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Patiño',
        cod_departamento: '035',
    },
    {
        id: 34042,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Pilagás',
        cod_departamento: '042',
    },
    {
        id: 34049,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Pilcomayo',
        cod_departamento: '049',
    },
    {
        id: 34056,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Pirané',
        cod_departamento: '056',
    },
    {
        id: 34063,
        provincia: 'Formosa',
        cod_provincia: '34',
        comuna: 'Ramón Lista',
        cod_departamento: '063',
    },
    {
        id: 38007,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Cochinoca',
        cod_departamento: '007',
    },
    {
        id: 38014,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'El Carmen',
        cod_departamento: '014',
    },
    {
        id: 38021,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Dr. Manuel Belgrano',
        cod_departamento: '021',
    },
    {
        id: 38028,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Humahuaca',
        cod_departamento: '028',
    },
    {
        id: 38035,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Ledesma',
        cod_departamento: '035',
    },
    {
        id: 38042,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Palpalá',
        cod_departamento: '042',
    },
    {
        id: 38049,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Rinconada',
        cod_departamento: '049',
    },
    {
        id: 38056,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'San Antonio',
        cod_departamento: '056',
    },
    {
        id: 38063,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'San Pedro',
        cod_departamento: '063',
    },
    {
        id: 38070,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Santa Bárbara',
        cod_departamento: '070',
    },
    {
        id: 38077,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Santa Catalina',
        cod_departamento: '077',
    },
    {
        id: 38084,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Susques',
        cod_departamento: '084',
    },
    {
        id: 38094,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Tilcara',
        cod_departamento: '094',
    },
    {
        id: 38098,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Tumbaya',
        cod_departamento: '098',
    },
    {
        id: 38105,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Valle Grande',
        cod_departamento: '105',
    },
    {
        id: 38112,
        provincia: 'Jujuy',
        cod_provincia: '38',
        comuna: 'Yavi',
        cod_departamento: '112',
    },
    {
        id: 42007,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Atreucó',
        cod_departamento: '007',
    },
    {
        id: 42014,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Caleu Caleu',
        cod_departamento: '014',
    },
    {
        id: 42021,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Capital',
        cod_departamento: '021',
    },
    {
        id: 42028,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Catriló',
        cod_departamento: '028',
    },
    {
        id: 42035,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Conhelo',
        cod_departamento: '035',
    },
    {
        id: 42042,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Curacó',
        cod_departamento: '042',
    },
    {
        id: 42049,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Chalileo',
        cod_departamento: '049',
    },
    {
        id: 42056,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Chapaleufú',
        cod_departamento: '056',
    },
    {
        id: 42063,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Chical Co',
        cod_departamento: '063',
    },
    {
        id: 42070,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Guatraché',
        cod_departamento: '070',
    },
    {
        id: 42077,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Hucal',
        cod_departamento: '077',
    },
    {
        id: 42084,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Lihuel Calel',
        cod_departamento: '084',
    },
    {
        id: 42091,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Limay Mahuida',
        cod_departamento: '091',
    },
    {
        id: 42098,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Loventué',
        cod_departamento: '098',
    },
    {
        id: 42105,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Maracó',
        cod_departamento: '105',
    },
    {
        id: 42112,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Puelén',
        cod_departamento: '112',
    },
    {
        id: 42119,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Quemú Quemú',
        cod_departamento: '119',
    },
    {
        id: 42126,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Rancul',
        cod_departamento: '126',
    },
    {
        id: 42133,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Realicó',
        cod_departamento: '133',
    },
    {
        id: 42140,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Toay',
        cod_departamento: '140',
    },
    {
        id: 42147,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Trenel',
        cod_departamento: '147',
    },
    {
        id: 42154,
        provincia: 'La Pampa',
        cod_provincia: '42',
        comuna: 'Utracán',
        cod_departamento: '154',
    },
    {
        id: 46007,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Arauco',
        cod_departamento: '007',
    },
    {
        id: 46014,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Capital',
        cod_departamento: '014',
    },
    {
        id: 46021,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Castro Barros',
        cod_departamento: '021',
    },
    {
        id: 46028,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Coronel Felipe Varela',
        cod_departamento: '028',
    },
    {
        id: 46035,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Chamical',
        cod_departamento: '035',
    },
    {
        id: 46042,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Chilecito',
        cod_departamento: '042',
    },
    {
        id: 46049,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Famatina',
        cod_departamento: '049',
    },
    {
        id: 46056,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'General Ángel V. Peñaloza',
        cod_departamento: '056',
    },
    {
        id: 46063,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'General Belgrano',
        cod_departamento: '063',
    },
    {
        id: 46070,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'General Juan Facundo Quiroga',
        cod_departamento: '070',
    },
    {
        id: 46077,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'General Lamadrid',
        cod_departamento: '077',
    },
    {
        id: 46084,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'General Ocampo',
        cod_departamento: '084',
    },
    {
        id: 46091,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'General San Martín',
        cod_departamento: '091',
    },
    {
        id: 46098,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Vinchina',
        cod_departamento: '098',
    },
    {
        id: 46105,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Independencia',
        cod_departamento: '105',
    },
    {
        id: 46112,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Rosario Vera Peñaloza',
        cod_departamento: '112',
    },
    {
        id: 46119,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'San Blas de los Sauces',
        cod_departamento: '119',
    },
    {
        id: 46126,
        provincia: 'La Rioja',
        cod_provincia: '46',
        comuna: 'Sanagasta',
        cod_departamento: '126',
    },
    {
        id: 50007,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Capital',
        cod_departamento: '007',
    },
    {
        id: 50014,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'General Alvear',
        cod_departamento: '014',
    },
    {
        id: 50021,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Godoy Cruz',
        cod_departamento: '021',
    },
    {
        id: 50028,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Guaymallén',
        cod_departamento: '028',
    },
    {
        id: 50035,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Junín',
        cod_departamento: '035',
    },
    {
        id: 50042,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'La Paz',
        cod_departamento: '042',
    },
    {
        id: 50049,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Las Heras',
        cod_departamento: '049',
    },
    {
        id: 50056,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Lavalle',
        cod_departamento: '056',
    },
    {
        id: 50063,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Luján de Cuyo',
        cod_departamento: '063',
    },
    {
        id: 50070,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Maipú',
        cod_departamento: '070',
    },
    {
        id: 50077,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Malargüe',
        cod_departamento: '077',
    },
    {
        id: 50084,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Rivadavia',
        cod_departamento: '084',
    },
    {
        id: 50091,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'San Carlos',
        cod_departamento: '091',
    },
    {
        id: 50098,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'San Martín',
        cod_departamento: '098',
    },
    {
        id: 50105,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'San Rafael',
        cod_departamento: '105',
    },
    {
        id: 50112,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Santa Rosa',
        cod_departamento: '112',
    },
    {
        id: 50119,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Tunuyán',
        cod_departamento: '119',
    },
    {
        id: 50126,
        provincia: 'Mendoza',
        cod_provincia: '50',
        comuna: 'Tupungato',
        cod_departamento: '126',
    },
    {
        id: 54007,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Apóstoles',
        cod_departamento: '007',
    },
    {
        id: 54014,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Cainguás',
        cod_departamento: '014',
    },
    {
        id: 54021,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Candelaria',
        cod_departamento: '021',
    },
    {
        id: 54028,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Capital',
        cod_departamento: '028',
    },
    {
        id: 54035,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Concepción',
        cod_departamento: '035',
    },
    {
        id: 54042,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Eldorado',
        cod_departamento: '042',
    },
    {
        id: 54049,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'General Manuel Belgrano',
        cod_departamento: '049',
    },
    {
        id: 54056,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Guaraní',
        cod_departamento: '056',
    },
    {
        id: 54063,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Iguazú',
        cod_departamento: '063',
    },
    {
        id: 54070,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Leandro N. Alem',
        cod_departamento: '070',
    },
    {
        id: 54077,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Libertador General San Martín',
        cod_departamento: '077',
    },
    {
        id: 54084,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Montecarlo',
        cod_departamento: '084',
    },
    {
        id: 54091,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'Oberá',
        cod_departamento: '091',
    },
    {
        id: 54098,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'San Ignacio',
        cod_departamento: '098',
    },
    {
        id: 54105,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'San Javier',
        cod_departamento: '105',
    },
    {
        id: 54112,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: 'San Pedro',
        cod_departamento: '112',
    },
    {
        id: 54119,
        provincia: 'Misiones',
        cod_provincia: '54',
        comuna: '25 de Mayo',
        cod_departamento: '119',
    },
    {
        id: 58007,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Aluminé',
        cod_departamento: '007',
    },
    {
        id: 58014,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Añelo',
        cod_departamento: '014',
    },
    {
        id: 58021,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Catán Lil',
        cod_departamento: '021',
    },
    {
        id: 58028,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Collón Curá',
        cod_departamento: '028',
    },
    {
        id: 58035,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Confluencia',
        cod_departamento: '035',
    },
    {
        id: 58042,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Chos Malal',
        cod_departamento: '042',
    },
    {
        id: 58049,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Huiliches',
        cod_departamento: '049',
    },
    {
        id: 58056,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Lácar',
        cod_departamento: '056',
    },
    {
        id: 58063,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Loncopué',
        cod_departamento: '063',
    },
    {
        id: 58070,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Los Lagos',
        cod_departamento: '070',
    },
    {
        id: 58077,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Minas',
        cod_departamento: '077',
    },
    {
        id: 58084,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Ñorquín',
        cod_departamento: '084',
    },
    {
        id: 58091,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Pehuenches',
        cod_departamento: '091',
    },
    {
        id: 58098,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Picún Leufú',
        cod_departamento: '098',
    },
    {
        id: 58105,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Picunches',
        cod_departamento: '105',
    },
    {
        id: 58112,
        provincia: 'Neuquén',
        cod_provincia: '58',
        comuna: 'Zapala',
        cod_departamento: '112',
    },
    {
        id: 62007,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Adolfo Alsina',
        cod_departamento: '007',
    },
    {
        id: 62014,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Avellaneda',
        cod_departamento: '014',
    },
    {
        id: 62021,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Bariloche',
        cod_departamento: '021',
    },
    {
        id: 62028,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Conesa',
        cod_departamento: '028',
    },
    {
        id: 62035,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'El Cuy',
        cod_departamento: '035',
    },
    {
        id: 62042,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'General Roca',
        cod_departamento: '042',
    },
    {
        id: 62049,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: '9 de Julio',
        cod_departamento: '049',
    },
    {
        id: 62056,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Ñorquincó',
        cod_departamento: '056',
    },
    {
        id: 62063,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Pichi Mahuida',
        cod_departamento: '063',
    },
    {
        id: 62070,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Pilcaniyeu',
        cod_departamento: '070',
    },
    {
        id: 62077,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'San Antonio',
        cod_departamento: '077',
    },
    {
        id: 62084,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: 'Valcheta',
        cod_departamento: '084',
    },
    {
        id: 62091,
        provincia: 'Río Negro',
        cod_provincia: '62',
        comuna: '25 de Mayo',
        cod_departamento: '091',
    },
    {
        id: 66007,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Anta',
        cod_departamento: '007',
    },
    {
        id: 66014,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Cachi',
        cod_departamento: '014',
    },
    {
        id: 66021,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Cafayate',
        cod_departamento: '021',
    },
    {
        id: 66028,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Capital',
        cod_departamento: '028',
    },
    {
        id: 66035,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Cerrillos',
        cod_departamento: '035',
    },
    {
        id: 66042,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Chicoana',
        cod_departamento: '042',
    },
    {
        id: 66049,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'General Güemes',
        cod_departamento: '049',
    },
    {
        id: 66056,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'General José de San Martín',
        cod_departamento: '056',
    },
    {
        id: 66063,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Guachipas',
        cod_departamento: '063',
    },
    {
        id: 66070,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Iruya',
        cod_departamento: '070',
    },
    {
        id: 66077,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'La Caldera',
        cod_departamento: '077',
    },
    {
        id: 66084,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'La Candelaria',
        cod_departamento: '084',
    },
    {
        id: 66091,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'La Poma',
        cod_departamento: '091',
    },
    {
        id: 66098,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'La Viña',
        cod_departamento: '098',
    },
    {
        id: 66105,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Los Andes',
        cod_departamento: '105',
    },
    {
        id: 66112,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Metán',
        cod_departamento: '112',
    },
    {
        id: 66119,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Molinos',
        cod_departamento: '119',
    },
    {
        id: 66126,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Orán',
        cod_departamento: '126',
    },
    {
        id: 66133,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Rivadavia',
        cod_departamento: '133',
    },
    {
        id: 66140,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Rosario de la Frontera',
        cod_departamento: '140',
    },
    {
        id: 66147,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Rosario de Lerma',
        cod_departamento: '147',
    },
    {
        id: 66154,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'San Carlos',
        cod_departamento: '154',
    },
    {
        id: 66161,
        provincia: 'Salta',
        cod_provincia: '66',
        comuna: 'Santa Victoria',
        cod_departamento: '161',
    },
    {
        id: 70007,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Albardón',
        cod_departamento: '007',
    },
    {
        id: 70014,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Angaco',
        cod_departamento: '014',
    },
    {
        id: 70021,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Calingasta',
        cod_departamento: '021',
    },
    {
        id: 70028,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Capital',
        cod_departamento: '028',
    },
    {
        id: 70035,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Caucete',
        cod_departamento: '035',
    },
    {
        id: 70042,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Chimbas',
        cod_departamento: '042',
    },
    {
        id: 70049,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Iglesia',
        cod_departamento: '049',
    },
    {
        id: 70056,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Jáchal',
        cod_departamento: '056',
    },
    {
        id: 70063,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: '9 de Julio',
        cod_departamento: '063',
    },
    {
        id: 70070,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Pocito',
        cod_departamento: '070',
    },
    {
        id: 70077,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Rawson',
        cod_departamento: '077',
    },
    {
        id: 70084,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Rivadavia',
        cod_departamento: '084',
    },
    {
        id: 70091,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'San Martín',
        cod_departamento: '091',
    },
    {
        id: 70098,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Santa Lucía',
        cod_departamento: '098',
    },
    {
        id: 70105,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Sarmiento',
        cod_departamento: '105',
    },
    {
        id: 70112,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Ullum',
        cod_departamento: '112',
    },
    {
        id: 70119,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Valle Fértil',
        cod_departamento: '119',
    },
    {
        id: 70126,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: '25 de Mayo',
        cod_departamento: '126',
    },
    {
        id: 70133,
        provincia: 'San Juan',
        cod_provincia: '70',
        comuna: 'Zonda',
        cod_departamento: '133',
    },
    {
        id: 74007,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Ayacucho',
        cod_departamento: '007',
    },
    {
        id: 74014,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Belgrano',
        cod_departamento: '014',
    },
    {
        id: 74021,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Coronel Pringles',
        cod_departamento: '021',
    },
    {
        id: 74028,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Chacabuco',
        cod_departamento: '028',
    },
    {
        id: 74035,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'General Pedernera',
        cod_departamento: '035',
    },
    {
        id: 74042,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Gobernador Dupuy',
        cod_departamento: '042',
    },
    {
        id: 74049,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Junín',
        cod_departamento: '049',
    },
    {
        id: 74056,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'La Capital',
        cod_departamento: '056',
    },
    {
        id: 74063,
        provincia: 'San Luis',
        cod_provincia: '74',
        comuna: 'Libertador General San Martín',
        cod_departamento: '063',
    },
    {
        id: 78007,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Corpen Aike',
        cod_departamento: '007',
    },
    {
        id: 78014,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Deseado',
        cod_departamento: '014',
    },
    {
        id: 78021,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Güer Aike',
        cod_departamento: '021',
    },
    {
        id: 78028,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Lago Argentino',
        cod_departamento: '028',
    },
    {
        id: 78035,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Lago Buenos Aires',
        cod_departamento: '035',
    },
    {
        id: 78042,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Magallanes',
        cod_departamento: '042',
    },
    {
        id: 78049,
        provincia: 'Santa Cruz',
        cod_provincia: '78',
        comuna: 'Río Chico',
        cod_departamento: '049',
    },
    {
        id: 82007,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Belgrano',
        cod_departamento: '007',
    },
    {
        id: 82014,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Caseros',
        cod_departamento: '014',
    },
    {
        id: 82021,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Castellanos',
        cod_departamento: '021',
    },
    {
        id: 82028,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Constitución',
        cod_departamento: '028',
    },
    {
        id: 82035,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Garay',
        cod_departamento: '035',
    },
    {
        id: 82042,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'General López',
        cod_departamento: '042',
    },
    {
        id: 82049,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'General Obligado',
        cod_departamento: '049',
    },
    {
        id: 82056,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Iriondo',
        cod_departamento: '056',
    },
    {
        id: 82063,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'La Capital',
        cod_departamento: '063',
    },
    {
        id: 82070,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Las Colonias',
        cod_departamento: '070',
    },
    {
        id: 82077,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: '9 de Julio',
        cod_departamento: '077',
    },
    {
        id: 82084,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Rosario',
        cod_departamento: '084',
    },
    {
        id: 82091,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'San Cristóbal',
        cod_departamento: '091',
    },
    {
        id: 82098,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'San Javier',
        cod_departamento: '098',
    },
    {
        id: 82105,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'San Jerónimo',
        cod_departamento: '105',
    },
    {
        id: 82112,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'San Justo',
        cod_departamento: '112',
    },
    {
        id: 82119,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'San Lorenzo',
        cod_departamento: '119',
    },
    {
        id: 82126,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'San Martín',
        cod_departamento: '126',
    },
    {
        id: 82133,
        provincia: 'Santa Fe',
        cod_provincia: '82',
        comuna: 'Vera',
        cod_departamento: '133',
    },
    {
        id: 86007,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Aguirre',
        cod_departamento: '007',
    },
    {
        id: 86014,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Alberdi',
        cod_departamento: '014',
    },
    {
        id: 86021,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Atamisqui',
        cod_departamento: '021',
    },
    {
        id: 86028,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Avellaneda',
        cod_departamento: '028',
    },
    {
        id: 86035,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Banda',
        cod_departamento: '035',
    },
    {
        id: 86042,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Belgrano',
        cod_departamento: '042',
    },
    {
        id: 86049,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Capital',
        cod_departamento: '049',
    },
    {
        id: 86056,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Copo',
        cod_departamento: '056',
    },
    {
        id: 86063,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Choya',
        cod_departamento: '063',
    },
    {
        id: 86070,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Figueroa',
        cod_departamento: '070',
    },
    {
        id: 86077,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'General Taboada',
        cod_departamento: '077',
    },
    {
        id: 86084,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Guasayán',
        cod_departamento: '084',
    },
    {
        id: 86091,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Jiménez',
        cod_departamento: '091',
    },
    {
        id: 86098,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Juan F. Ibarra',
        cod_departamento: '098',
    },
    {
        id: 86105,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Loreto',
        cod_departamento: '105',
    },
    {
        id: 86112,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Mitre',
        cod_departamento: '112',
    },
    {
        id: 86119,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Moreno',
        cod_departamento: '119',
    },
    {
        id: 86126,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Ojo de Agua',
        cod_departamento: '126',
    },
    {
        id: 86133,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Pellegrini',
        cod_departamento: '133',
    },
    {
        id: 86140,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Quebrachos',
        cod_departamento: '140',
    },
    {
        id: 86147,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Río Hondo',
        cod_departamento: '147',
    },
    {
        id: 86154,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Rivadavia',
        cod_departamento: '154',
    },
    {
        id: 86161,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Robles',
        cod_departamento: '161',
    },
    {
        id: 86168,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Salavina',
        cod_departamento: '168',
    },
    {
        id: 86175,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'San Martín',
        cod_departamento: '175',
    },
    {
        id: 86182,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Sarmiento',
        cod_departamento: '182',
    },
    {
        id: 86189,
        provincia: 'Santiago del Estero',
        cod_provincia: '86',
        comuna: 'Silípica',
        cod_departamento: '189',
    },
    {
        id: 90007,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Burruyacú',
        cod_departamento: '007',
    },
    {
        id: 90014,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Cruz Alta',
        cod_departamento: '014',
    },
    {
        id: 90021,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Chicligasta',
        cod_departamento: '021',
    },
    {
        id: 90028,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Famaillá',
        cod_departamento: '028',
    },
    {
        id: 90035,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Graneros',
        cod_departamento: '035',
    },
    {
        id: 90042,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Juan B. Alberdi',
        cod_departamento: '042',
    },
    {
        id: 90049,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'La Cocha',
        cod_departamento: '049',
    },
    {
        id: 90056,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Leales',
        cod_departamento: '056',
    },
    {
        id: 90063,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Lules',
        cod_departamento: '063',
    },
    {
        id: 90070,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Monteros',
        cod_departamento: '070',
    },
    {
        id: 90077,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Río Chico',
        cod_departamento: '077',
    },
    {
        id: 90084,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Capital',
        cod_departamento: '084',
    },
    {
        id: 90091,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Simoca',
        cod_departamento: '091',
    },
    {
        id: 90098,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Tafí del Valle',
        cod_departamento: '098',
    },
    {
        id: 90105,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Tafí Viejo',
        cod_departamento: '105',
    },
    {
        id: 90112,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Trancas',
        cod_departamento: '112',
    },
    {
        id: 90119,
        provincia: 'Tucumán',
        cod_provincia: '90',
        comuna: 'Yerba Buena',
        cod_departamento: '119',
    },
]
