import { Paciente } from '@/interfaces/user.interface'

export const pacientes: Paciente[] = [
    {
        id: 8005,
        firstName: 'Juan',
        lastName: 'Perez',
        city: 'Mar del Plata',
        province: 'Buenos Aires',
        email: 'juanperez@gmail.com',
        factorSanguineo: 'A+',
        fechaNacimiento: '1991-12-03',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 321321,
        phone: '351351531',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'MASCULINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8006,
        firstName: 'Maria',
        lastName: 'Gonzalez',
        city: 'Rosario',
        province: 'Santa Fe',
        email: 'mariagonzalez@gmail.com',
        factorSanguineo: 'B+',
        fechaNacimiento: '1985-07-15',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 654654,
        phone: '123456789',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'FEMENINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Donante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8007,
        firstName: 'Carlos',
        lastName: 'Ramirez',
        city: 'Córdoba',
        province: 'Córdoba',
        email: 'carlosramirez@gmail.com',
        factorSanguineo: 'O-',
        fechaNacimiento: '1978-03-22',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 789789,
        phone: '987654321',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'MASCULINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Trasplantado',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8008,
        firstName: 'Laura',
        lastName: 'Martinez',
        city: 'Mendoza',
        province: 'Mendoza',
        email: 'lauramartinez@gmail.com',
        factorSanguineo: 'AB+',
        fechaNacimiento: '1990-11-01',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 321654,
        phone: '456789123',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'FEMENINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8009,
        firstName: 'Jorge',
        lastName: 'Fernandez',
        city: 'La Plata',
        province: 'Buenos Aires',
        email: 'jorgefernandez@gmail.com',
        factorSanguineo: 'A-',
        fechaNacimiento: '1982-06-30',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 987321,
        phone: '321654987',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'MASCULINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8010,
        firstName: 'Ana',
        lastName: 'Lopez',
        city: 'Salta',
        province: 'Salta',
        email: 'analopez@gmail.com',
        factorSanguineo: 'B-',
        fechaNacimiento: '1995-09-17',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 654987,
        phone: '789123456',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'FEMENINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8011,
        firstName: 'Pedro',
        lastName: 'Garcia',
        city: 'San Juan',
        province: 'San Juan',
        email: 'pedrogarcia@gmail.com',
        factorSanguineo: 'O+',
        fechaNacimiento: '1987-12-25',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 123987,
        phone: '654321987',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'MASCULINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8012,
        firstName: 'Lucia',
        lastName: 'Sanchez',
        city: 'Tucumán',
        province: 'Tucumán',
        email: 'luciasanchez@gmail.com',
        factorSanguineo: 'A+',
        fechaNacimiento: '1992-08-14',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 456123,
        phone: '123789456',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'FEMENINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8013,
        firstName: 'Roberto',
        lastName: 'Diaz',
        city: 'Posadas',
        province: 'Misiones',
        email: 'robertodiaz@gmail.com',
        factorSanguineo: 'B+',
        fechaNacimiento: '1975-05-05',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 789123,
        phone: '987321654',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'MASCULINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8014,
        firstName: 'Elena',
        lastName: 'Mendez',
        city: 'Resistencia',
        province: 'Chaco',
        email: 'elenamendez@gmail.com',
        factorSanguineo: 'AB-',
        fechaNacimiento: '1980-04-20',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 987654,
        phone: '321987654',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'FEMENINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
    {
        id: 8015,
        firstName: 'Francisco',
        lastName: 'Ortiz',
        city: 'San Miguel',
        province: 'Tucumán',
        email: 'franciscoortiz@gmail.com',
        factorSanguineo: 'O-',
        fechaNacimiento: '1991-01-13',
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        nroDocumento: 456789,
        phone: '123456987',
        deseaDonar: true,
        donanteActivo: true,
        sex: 'MASCULINO',
        medicId: null,
        patientId: 2,
        estadoDelPaciente: 'Pre-trasplante',
        organoEnfermo: 'Riñón',
    },
]
