import { MedicosDisponibles } from '@/interfaces/medico-disponible.interface'
export const medicosDisponibles: MedicosDisponibles[] = [
    {
        id: 123123123,
        fecha: '04/08/2024',
        photo: '/img/samples/doctor.png',
        lastname: 'Alvarez',
        firstName: 'Julian',
        especialidad: 'Gastrología',
        lugarAtencion: 'Clínica San Diedo',
        horaAtencion: '9:00 Hs',
    },
    {
        id: 123123124,
        fecha: '04/08/2024',
        photo: '/img/samples/doctor.png',
        lastname: 'Alvarez',
        firstName: 'Julian',
        especialidad: 'Gastrología',
        lugarAtencion: 'Clínica San Diedo',
        horaAtencion: '11:00 Hs',
    },
    {
        id: 123123125,
        fecha: '05/08/2024',
        photo: '/img/samples/doctor.png',
        lastname: 'Alvarez',
        firstName: 'Julian',
        especialidad: 'Gastrología',
        lugarAtencion: 'Clínica San Diedo',
        horaAtencion: '12:00 Hs',
    },
    {
        id: 123123126,
        fecha: '06/08/2024',
        photo: '/img/samples/doctor.png',
        lastname: 'Perez',
        firstName: 'Sergio',
        especialidad: 'Gastrología',
        lugarAtencion: 'Clínica San Diedo',
        horaAtencion: '12:00 Hs',
    },
]
