import { Paciente } from '@/interfaces/user.interface'

export const pacientes: Paciente[] = [
    {
        id: 8005,
        firstName: 'Juan',
        lastname: 'Perez',
        city: 'Mar del Plata',
        province: 'Buenos Aires',
        email: 'juanperez@gmail.com',
        factorSanguineo: 'A+',
        fechaNacimiento: new Date('1991-12-03'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        nroDocumento: 321321,
        prepaga: '110626',
        patologia: 'C62',
        phone: '351351531',
    },
    {
        id: 8006,
        firstName: 'Maria',
        lastname: 'Gonzalez',
        city: 'Rosario',
        province: 'Santa Fe',
        email: 'mariagonzalez@gmail.com',
        factorSanguineo: 'B+',
        fechaNacimiento: new Date('1985-07-15'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        nroDocumento: 654654,
        prepaga: '220733',
        patologia: 'E11',
        phone: '123456789',
    },
    {
        id: 8007,
        firstName: 'Carlos',
        lastname: 'Ramirez',
        city: 'Córdoba',
        province: 'Córdoba',
        email: 'carlosramirez@gmail.com',
        factorSanguineo: 'O-',
        fechaNacimiento: new Date('1978-03-22'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        nroDocumento: 789789,
        prepaga: '330844',
        patologia: 'I10',
        phone: '987654321',
    },
    {
        id: 8008,
        firstName: 'Laura',
        lastname: 'Martinez',
        city: 'Mendoza',
        province: 'Mendoza',
        email: 'lauramartinez@gmail.com',
        factorSanguineo: 'AB+',
        fechaNacimiento: new Date('1990-11-01'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        nroDocumento: 321654,
        prepaga: '440955',
        patologia: 'J45',
        phone: '456789123',
    },
    {
        id: 8009,
        firstName: 'Jorge',
        lastname: 'Fernandez',
        city: 'La Plata',
        province: 'Buenos Aires',
        email: 'jorgefernandez@gmail.com',
        factorSanguineo: 'A-',
        fechaNacimiento: new Date('1982-06-30'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        nroDocumento: 987321,
        prepaga: '550066',
        patologia: 'K35',
        phone: '321654987',
    },
    {
        id: 8010,
        firstName: 'Ana',
        lastname: 'Lopez',
        city: 'Salta',
        province: 'Salta',
        email: 'analopez@gmail.com',
        factorSanguineo: 'B-',
        fechaNacimiento: new Date('1995-09-17'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        nroDocumento: 654987,
        prepaga: '660177',
        patologia: 'N18',
        phone: '789123456',
    },
    {
        id: 8011,
        firstName: 'Pedro',
        lastname: 'Garcia',
        city: 'San Juan',
        province: 'San Juan',
        email: 'pedrogarcia@gmail.com',
        factorSanguineo: 'O+',
        fechaNacimiento: new Date('1987-12-25'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        nroDocumento: 123987,
        prepaga: '770288',
        patologia: 'C34',
        phone: '654321987',
    },
    {
        id: 8012,
        firstName: 'Lucia',
        lastname: 'Sanchez',
        city: 'Tucumán',
        province: 'Tucumán',
        email: 'luciasanchez@gmail.com',
        factorSanguineo: 'A+',
        fechaNacimiento: new Date('1992-08-14'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        nroDocumento: 456123,
        prepaga: '880399',
        patologia: 'E66',
        phone: '123789456',
    },
    {
        id: 8013,
        firstName: 'Roberto',
        lastname: 'Diaz',
        city: 'Posadas',
        province: 'Misiones',
        email: 'robertodiaz@gmail.com',
        factorSanguineo: 'B+',
        fechaNacimiento: new Date('1975-05-05'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        nroDocumento: 789123,
        prepaga: '990411',
        patologia: 'M54',
        phone: '987321654',
    },
    {
        id: 8014,
        firstName: 'Elena',
        lastname: 'Mendez',
        city: 'Resistencia',
        province: 'Chaco',
        email: 'elenamendez@gmail.com',
        factorSanguineo: 'AB-',
        fechaNacimiento: new Date('1980-04-20'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        nroDocumento: 987654,
        prepaga: '110522',
        patologia: 'I20',
        phone: '321987654',
    },
    {
        id: 8015,
        firstName: 'Francisco',
        lastname: 'Ortiz',
        city: 'San Miguel',
        province: 'Tucumán',
        email: 'franciscoortiz@gmail.com',
        factorSanguineo: 'O-',
        fechaNacimiento: new Date('1991-01-13'),
        photo: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        nroDocumento: 456789,
        prepaga: '220633',
        patologia: 'E03',
        phone: '123456987',
    },
]
