import { Paciente } from '@/interfaces/user.interface'

export const pacientes: Paciente[] = [
    {
        id: 8005,
        name: 'Juan',
        lastname: 'Perez',
        ciudad: 'Mar del Plata',
        provincia: 'Buenos Aires',
        email: 'juanperez@gmail.com',
        factorSanguineo: 'A+',
        fechaNacimiento: new Date('1991-12-03'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        entidadId: 321321,
        financiadorId: 110626,
        numeroDocumento: 321321321,
        patologiaId: 'C62',
        personalMedicoId: undefined,
        phoneNumber: 351351531,
        tipoDocumentoId: 32132123,
    },
    {
        id: 8006,
        name: 'Maria',
        lastname: 'Gonzalez',
        ciudad: 'Rosario',
        provincia: 'Santa Fe',
        email: 'mariagonzalez@gmail.com',
        factorSanguineo: 'B+',
        fechaNacimiento: new Date('1985-07-15'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        entidadId: 654654,
        financiadorId: 220733,
        numeroDocumento: 654654654,
        patologiaId: 'E11',
        personalMedicoId: 101,
        phoneNumber: 123456789,
        tipoDocumentoId: 65465412,
    },
    {
        id: 8007,
        name: 'Carlos',
        lastname: 'Ramirez',
        ciudad: 'Córdoba',
        provincia: 'Córdoba',
        email: 'carlosramirez@gmail.com',
        factorSanguineo: 'O-',
        fechaNacimiento: new Date('1978-03-22'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        entidadId: 789789,
        financiadorId: 330844,
        numeroDocumento: 789789789,
        patologiaId: 'I10',
        personalMedicoId: 102,
        phoneNumber: 987654321,
        tipoDocumentoId: 78978945,
    },
    {
        id: 8008,
        name: 'Laura',
        lastname: 'Martinez',
        ciudad: 'Mendoza',
        provincia: 'Mendoza',
        email: 'lauramartinez@gmail.com',
        factorSanguineo: 'AB+',
        fechaNacimiento: new Date('1990-11-01'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        entidadId: 321654,
        financiadorId: 440955,
        numeroDocumento: 321654987,
        patologiaId: 'J45',
        personalMedicoId: 103,
        phoneNumber: 456789123,
        tipoDocumentoId: 32165478,
    },
    {
        id: 8009,
        name: 'Jorge',
        lastname: 'Fernandez',
        ciudad: 'La Plata',
        provincia: 'Buenos Aires',
        email: 'jorgefernandez@gmail.com',
        factorSanguineo: 'A-',
        fechaNacimiento: new Date('1982-06-30'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        entidadId: 987321,
        financiadorId: 550066,
        numeroDocumento: 987321654,
        patologiaId: 'K35',
        personalMedicoId: 104,
        phoneNumber: 321654987,
        tipoDocumentoId: 98732112,
    },
    {
        id: 8010,
        name: 'Ana',
        lastname: 'Lopez',
        ciudad: 'Salta',
        provincia: 'Salta',
        email: 'analopez@gmail.com',
        factorSanguineo: 'B-',
        fechaNacimiento: new Date('1995-09-17'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        entidadId: 654987,
        financiadorId: 660177,
        numeroDocumento: 654987321,
        patologiaId: 'N18',
        personalMedicoId: 105,
        phoneNumber: 789123456,
        tipoDocumentoId: 65498745,
    },
    {
        id: 8011,
        name: 'Pedro',
        lastname: 'Garcia',
        ciudad: 'San Juan',
        provincia: 'San Juan',
        email: 'pedrogarcia@gmail.com',
        factorSanguineo: 'O+',
        fechaNacimiento: new Date('1987-12-25'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        entidadId: 123987,
        financiadorId: 770288,
        numeroDocumento: 123987654,
        patologiaId: 'C34',
        personalMedicoId: 106,
        phoneNumber: 654321987,
        tipoDocumentoId: 12398712,
    },
    {
        id: 8012,
        name: 'Lucia',
        lastname: 'Sanchez',
        ciudad: 'Tucumán',
        provincia: 'Tucumán',
        email: 'luciasanchez@gmail.com',
        factorSanguineo: 'A+',
        fechaNacimiento: new Date('1992-08-14'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        entidadId: 456123,
        financiadorId: 880399,
        numeroDocumento: 456123789,
        patologiaId: 'E66',
        personalMedicoId: 107,
        phoneNumber: 123789456,
        tipoDocumentoId: 45612345,
    },
    {
        id: 8013,
        name: 'Roberto',
        lastname: 'Diaz',
        ciudad: 'Posadas',
        provincia: 'Misiones',
        email: 'robertodiaz@gmail.com',
        factorSanguineo: 'B+',
        fechaNacimiento: new Date('1975-05-05'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        entidadId: 789123,
        financiadorId: 990411,
        numeroDocumento: 789123654,
        patologiaId: 'M54',
        personalMedicoId: 108,
        phoneNumber: 987321654,
        tipoDocumentoId: 78912378,
    },
    {
        id: 8014,
        name: 'Elena',
        lastname: 'Mendez',
        ciudad: 'Resistencia',
        provincia: 'Chaco',
        email: 'elenamendez@gmail.com',
        factorSanguineo: 'AB-',
        fechaNacimiento: new Date('1980-04-20'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'F',
        entidadId: 987654,
        financiadorId: 110522,
        numeroDocumento: 987654321,
        patologiaId: 'I20',
        personalMedicoId: 109,
        phoneNumber: 321987654,
        tipoDocumentoId: 98765478,
    },
    {
        id: 8015,
        name: 'Francisco',
        lastname: 'Ortiz',
        ciudad: 'San Miguel',
        provincia: 'Tucumán',
        email: 'franciscoortiz@gmail.com',
        factorSanguineo: 'O-',
        fechaNacimiento: new Date('1991-01-13'),
        img: '/img/samples/paciente.png',
        role: 'PACIENTE',
        sexo: 'M',
        entidadId: 456789,
        financiadorId: 220633,
        numeroDocumento: 456789123,
        patologiaId: 'E03',
        personalMedicoId: 110,
        phoneNumber: 123456987,
        tipoDocumentoId: 45678912,
    },
]
